# Generated by Django 6.0.3 on 2026-07-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_game_difficulty'),
        ('chess_app', '0003_alter_game_black_player_alter_game_white_player'),
    ]

    operations = [
    ]
