# Generated by Django 6.0.3 on 2026-07-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0004_merge_20260715_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='difficulty',
        ),
    ]
