# basic nginx configuration for reverse proxy to Django backend

events {}

# define backend service (django container in docker network)
http {
    upstream django_backend {
        server backend:8000;
    }

# redirect all traffic to https
    server {
        listen 80;
        server_name localhost;

        # Metrics endpoint for nginx exporter inside Docker network
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.16.0.0/12;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            deny all;
        }

        # force https for regular traffic while keeping /nginx_status on plain HTTP
        location / {
            return 301 https://$host:8443$request_uri;
        }
    }

    # https server (reverse proxy to django backend)
    server {
        listen 443 ssl;
        server_name localhost;

        # self assigned certs for local development (replace with valid certs in production)
        ssl_certificate /etc/nginx/certs/local.crt;
        ssl_certificate_key /etc/nginx/certs/local.key;

        # forward all incoming requests to django backend 
        location / {
            proxy_pass http://django_backend;

            # preserve original request headers for proper handling by django
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;

            # forward client's IP chain
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # tell django backend that the original request was https (important for secure cookies and redirects)
            proxy_set_header X-Forwarded-Proto https;
        }

        # Internal metrics endpoint for nginx-prometheus-exporter
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.16.0.0/12;
            allow 10.0.0.0/8;
            allow 192.168.0.0/16;
            deny all;
        }
    }
}
