# Generated by Django 6.0.3 on 2026-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_avatar',
            field=models.URLField(blank=True, default=''),
        ),
    ]
