# Generated by Django 6.0.3 on 2026-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendship_created_at_friendship_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='users_match_white_p_d48257_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='users_match_black_p_00bdf7_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='users_match_status_859797_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='users_tourn_status_ef1b98_idx',
        ),
        migrations.RemoveIndex(
            model_name='tournament',
            name='users_tourn_start_d_12a2b0_idx',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='elo',
            field=models.IntegerField(default=1200),
        ),
        migrations.AlterField(
            model_name='user',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='winner',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
