# Generated by Django 6.0.3 on 2026-07-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0006_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
    ]
